version: 2

jobs:
  deploy-docs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: build site?
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            echo "Commit range" $COMMIT_RANGE
            echo "Changed files:"
            git diff --name-only $COMMIT_RANGE
            echo
            if [[ $(git diff --name-only $COMMIT_RANGE | grep -E '^(docs/|\.circleci/config.yml)') != "" ]]
            then
              echo "Building docs"
              cd docs
              npm install
              npx lumo compile.cljs
              echo
              git clone https://${GH_TOKEN}@github.com/domino-clj/domino-clj.github.io.git
              echo
              echo "Copying files to GH pages repo"
              cp -r out/* domino-clj.github.io/
              cd domino-clj.github.io
              git config user.email "carmen.wla@gmail.com"
              git config user.name "Carmen La"
              git diff-index --quiet HEAD || (git add --all && git commit -am "$CIRCLE_BUILD_URL" && git push --force origin master)
            else
              echo "No changes to docs/ folder, ending build"
            fi

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docs:
          filters:
            branches:
              only:
                - master
