version: 2

jobs:
  deploy-docs:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: build site?
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            echo "Commit range" $COMMIT_RANGE
            echo
            if [[ $(git diff --name-only $COMMIT_RANGE | grep -E '^(README.md|docs/|\.circleci/config.yml)') != "" ]]
            then
              echo "Building docs"
              cd docs
              npm install
              npx lumo compile.cljs
              echo
              git clone https://${GH_TOKEN}@github.com/domino-clj/domino-clj.github.io.git
              echo
              echo "Copying files to GH pages repo"
              cp -r out/* domino-clj.github.io/
              cd domino-clj.github.io
              git config user.email "carmen.wla@gmail.com"
              git config user.name "Carmen La"
              git diff-index --quiet HEAD || (git add --all && git commit -am "$CIRCLE_BUILD_URL" && git push --force origin master)
            else
              echo "No changes to docs/ folder or README.md, ending build"
            fi

  test:
    docker:
      - image: circleci/clojure:lein-2.9.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "project.clj"}}
      - save_cache:
          paths:
            - ~/.m2
          key: deps-{{ checksum "project.clj"}}
      - run:
          name: test clj
          command: lein test2junit
      - run:
          name: test cljs
          command: lein with-profile test doo node once
      - store_test_results:
          path: "target/test2junit"


workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy-docs:
          requires:
            - test
          filters:
            branches:
              only:
                - master
